// TODO: Create a function that returns the license link
// If there is no license, return an empty string

// TODO: Create a function that returns the license section of README
// If there is no license, return an empty string

// TODO: Create a function to generate markdown for README and Create Licensses
/* 
 `[![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)\n\n`;
    '(https://opensource.org/licenses/MIT);
 } "Apache") {
   `[![License](https://img.shields.io/badge/License-Apache%202.0-blue.svg)](https://opensource.org/licenses/Apache-2.0)\n\n`;
    '(http://www.apache.org/licenses/LICENSE-2.0.html)
 } "GPLv3") {
    `[![License: GPL v3](https://img.shields.io/badge/License-GPLv3-blue.svg)](https://www.gnu.org/licenses/gpl-3.0)\n\n`;
   '(http://www.gnu.org/licenses/gpl-3.0.html)
 */

/////// This is the function for the generateMarkdown that will populate the README.md file/////////////////////////

function generateMarkdown(answers) {
  return `
  <h1 align='center'>${answers.protjectTitle}<h1/> 

  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />

  ## Description
  ${answers.description}

  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)
  
  ## Installation
  ${answers.installation}

  ## Usage
  ${answers.usage}

  ## License
  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
  <br />
  This application is covered by the ${answers.license} license. 

  ## Contributing
   ${answers.contributing}
   
  ## Tests
  ${answers.tests}

  ##Questions 
  ${answers.questions}<br/>
  <br/>
  My Github address [${answers.username}](https://github.com/${answers.username})<br />
  <br/>
  My E-mail address: ${answers.emial}<br/><br/>
  _This README was generated by Matthew L. Boisse
  
  `;
}
module.exports = generateMarkdown;