
// this will return the badge based on what is selected and in none it will return an empty string 
function createLicenseBadge(license) {
  if (license !== 'None') {
    return `![GitHub license](https://img.shields.io/badge/license-${license}-blue.svg)`
  } else {
    return ""
  }
}

//this will return the license link and if there is none it will return an empty string 
function createLicenseLink(license) {
  if (license !== 'None') {
    return `[License Link](http://choosealicense.com/licenses)`
  } else {
    return "";
  }
}

// this reneders the license to the actual readme
function createLicenseSection(license) {
  if (license !== 'None') {
    return `
    ${license}`
  } else{
    return ""
  }
}




//This will create a function to generate the markdown for the readme file.
function generateMarkdown(answers) {
  const licenseBadge = createLicenseBadge(data.license);
  const licenseLink = createLicenseLink(data.license);
  const licenseSection = createLicenseSection(data.license);

  return `
${licenseBadge}
 ${licenseLink}

  <h1 align='center'>${answers.projectTitle}<h1/> 


  ## Description
  ${answers.description}

  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)
  
  ## Installation
  ${answers.installation}

  ## Usage
  ${answers.usage}

  ## License
 ${data.license}

  ## Contributing
   ${answers.contributing}
   
  ##Questions 
  ${answers.questions}<br/>
  <br/>

  My Github address [${answers.username}](https://github.com/${answers.username})<br />

  <br/>
  My E-mail address: ${answers.email}<br/><br/>

  _This README was generated by Matthew L. Boisse
  
  `;
}
module.exports = generateMarkdown;