
/////// This is the function for the generateMarkdown that will populate the README.md file/////////////////////////

function generateMarkdown(answers) {
  return `
  <h1 align='center'>${answers.projectTitle}<h1/> 

  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)<br />

  ## Description
  ${answers.description}

  ## Table of Contents
  - [Description](#description)
  - [Installation](#installation)
  - [Usage](#usage)
  - [License](#license)
  - [Contributing](#contributing)
  - [Tests](#tests)
  - [Questions](#questions)
  
  ## Installation
  ${answers.installation}

  ## Usage
  ${answers.usage}

  ## License
  ![badge](https://img.shields.io/badge/license-${answers.license}-brightgreen)
  <br />
  This application is covered by the ${answers.license} license. 

  ## Contributing
   ${answers.contributing}
   
  ##Questions 
  ${answers.questions}<br/>
  <br/>

  My Github address [${answers.username}](https://github.com/${answers.username})<br />

  <br/>
  My E-mail address: ${answers.email}<br/><br/>

  _This README was generated by Matthew L. Boisse
  
  `;
}
module.exports = generateMarkdown;